import { ChangeDetectionStrategy, Component, DestroyRef, effect, inject, input, output, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { firstValueFrom, lastValueFrom } from 'rxjs';
import { Room } from 'livekit-client';
import { Router } from '@angular/router';
import { ApiService } from '../../core/api/api.service';
import { AuthStore } from '../../core/auth/auth.store';
import { NotificationStore } from '../../core/notifications/notification.store';
import { PreferencesService } from '../../core/preferences/preferences.service';
import { VoiceService } from '../../core/voice/voice.service';
import { AvatarComponent } from '../../shared/avatar/avatar.component';
import type { SecuritySession } from '../../core/api/models';

type AccountTab = 'profile' | 'settings' | 'security' | 'customization';

@Component({
  selector: 'app-account-dialog', changeDetection: ChangeDetectionStrategy.OnPush, imports: [ReactiveFormsModule, AvatarComponent, DatePipe],
  template: `
    @if (open()) {
      <div class="dialog-backdrop account-dialog-backdrop" animate.leave="dialog-leave" (click)="closeBackdrop($event)"><section class="account-dialog" role="dialog" aria-modal="true" aria-labelledby="account-dialog-heading">
        <div class="account-dialog__panel"><nav class="account-dialog__nav" aria-label="Разделы аккаунта"><strong>Аккаунт</strong>
          @for (item of tabs; track item.id) { <button type="button" [class.security-alert]="item.id === 'security' && auth.user()?.security?.alert" [attr.data-active]="tab() === item.id" (click)="selectTab(item.id)">{{ item.label }}</button> }
        </nav><div class="account-dialog__content"><header class="account-dialog__header"><strong id="account-dialog-heading">{{ heading() }}</strong><button type="button" aria-label="Закрыть" (click)="closed.emit()">×</button></header>
          @if (tab() === 'profile') {
            <section id="account-profile-panel" class="account-dialog__section"><div class="profile-edit-preview">
              <app-avatar class="profile-avatar profile-avatar--large" [src]="previewUrl() || auth.user()?.avatar || ''" [label]="profileForm.controls.displayName.value || auth.user()?.display_name || 'Профиль'" />
              <label class="avatar-picker-button" for="account-avatar-file" aria-label="Выбрать аватар"><img src="/avatar-select.svg" alt=""></label><strong>{{ auth.user()?.email }}</strong></div>
              <form id="account-profile-form" class="auth-form" [formGroup]="profileForm" (ngSubmit)="saveProfile()"><label for="account-display-name">Имя</label><input id="account-display-name" type="text" formControlName="displayName" maxlength="50" autocomplete="name">
                <input id="account-avatar-file" class="visually-hidden-file" type="file" accept="image/png,image/jpeg,image/gif,image/webp" (change)="pickAvatar($event)"><div class="profile-actions">
                  <button class="button button--secondary" type="button" [disabled]="pending() || !auth.user()?.avatar" (click)="deleteAvatar()">Удалить аватар</button><button class="button button--secondary" type="button" [disabled]="pending()" (click)="logout()">Выйти из аккаунта</button><button id="account-save-profile" class="button button--primary" type="submit" [disabled]="profileForm.invalid || !profileChanged() || pending()">{{ pending() ? 'Сохраняем…' : 'Сохранить' }}</button>
                </div></form><div class="profile-danger-zone"><span>Опасная зона</span><button class="profile-danger-zone__delete" type="button" aria-label="Удалить аккаунт" (click)="deleteConfirmOpen.set(true)"><img src="/trash.svg" alt=""></button></div>
                @if (progress() > 0 && progress() < 100) { <div class="upload-progress"><span [style.width.%]="progress()"></span></div> }
            </section>
          } @else if (tab() === 'settings') {
            <section class="account-dialog__section settings-panel settings-panel--dialog" [formGroup]="settingsForm"><section><h2>Звук</h2>
              <label>Микрофон<select formControlName="inputDeviceId"><option value="">Системный микрофон</option>@for (device of inputs(); track device.deviceId) { <option [value]="device.deviceId">{{ device.label || 'Микрофон' }}</option> }</select></label><label>Динамики<select formControlName="outputDeviceId"><option value="">Системные динамики</option>@for (device of outputs(); track device.deviceId) { <option [value]="device.deviceId">{{ device.label || 'Динамики' }}</option> }</select></label>
              <label class="settings-toggle"><input type="checkbox" formControlName="microphoneEnabled"><span>Включать микрофон при входе в комнату</span></label><button type="button" [disabled]="loading()" (click)="loadDevices()">{{ loading() ? 'Обновляем…' : 'Обновить устройства' }}</button>
            </section><section><h2>Интерфейс</h2><label class="settings-toggle"><input type="checkbox" formControlName="debugErrors"><span>Показывать DEBUG-ошибки</span></label></section></section>
          } @else if (tab() === 'security') { <section class="account-dialog__section security-panel"><section><h2>Смена пароля</h2><p>Новый сеанс сможет менять пароль через 24 часа после входа.</p><form class="auth-form" [formGroup]="passwordForm" (ngSubmit)="changePassword()"><label for="account-password">Новый пароль</label><input id="account-password" type="password" formControlName="password" autocomplete="new-password" maxlength="72" placeholder="От 6 до 72 символов"><button class="button button--primary" type="submit" [disabled]="passwordForm.invalid || pending() || !canManageSecurity()">{{ pending() ? 'Сохраняем…' : 'Сменить пароль' }}</button></form></section>@if (canManageSecurity()) { <section><h2>Устройства</h2><p>Активные сеансы. Открытие списка подтверждает новый вход.</p>@if (sessionsLoading()) { <p>Загружаем сеансы…</p> } @else { <ul class="security-sessions">@for (item of sessions(); track item.id) { <li><div><strong>{{ item.current ? 'Этот сеанс' : 'Сеанс в браузере' }}</strong><small>Вход: {{ item.created_at | date:'short' }} · Активность: {{ item.last_seen_at | date:'short' }}</small></div><button type="button" class="button button--secondary" [disabled]="pending() || item.current" (click)="revokeSession(item)">Завершить сеанс</button></li> }</ul> }</section> } @else { <p class="security-panel__locked">Список устройств доступен через 24 часа после входа.</p> }</section>
          } @else { <section class="account-dialog__section customization-panel"><h2>Темы</h2><p class="customization-panel__intro">Выберите оформление интерфейса.</p><div class="customization-panel__themes" role="radiogroup" aria-label="Тема интерфейса"><label class="customization-panel__theme" [attr.data-active]="preferences.theme() === 'dark'"><input type="radio" name="account-theme" value="dark" [checked]="preferences.theme() === 'dark'" (change)="setTheme('dark')"><span><strong>Тёмная</strong><small>Нейтральная тёмная тема.</small></span><i class="customization-panel__theme-preview customization-panel__theme-preview--dark" aria-hidden="true"><b></b><b></b><b></b></i></label><label class="customization-panel__theme" [attr.data-active]="preferences.theme() === 'light'"><input type="radio" name="account-theme" value="light" [checked]="preferences.theme() === 'light'" (change)="setTheme('light')"><span><strong>Светлая</strong><small>Светлая тема для ярких помещений.</small></span><i class="customization-panel__theme-preview customization-panel__theme-preview--light" aria-hidden="true"><b></b><b></b><b></b></i></label><label class="customization-panel__theme" [attr.data-active]="preferences.theme() === 'forest'"><input type="radio" name="account-theme" value="forest" [checked]="preferences.theme() === 'forest'" (change)="setTheme('forest')"><span><strong>Лесная</strong><small>Хвойная палитра с моховыми акцентами.</small></span><i class="customization-panel__theme-preview customization-panel__theme-preview--forest" aria-hidden="true"><b></b><b></b><b></b></i></label><label class="customization-panel__theme" [attr.data-active]="preferences.theme() === 'burgundy'"><input type="radio" name="account-theme" value="burgundy" [checked]="preferences.theme() === 'burgundy'" (change)="setTheme('burgundy')"><span><strong>Бордовая</strong><small>Глубокая винная палитра.</small></span><i class="customization-panel__theme-preview customization-panel__theme-preview--burgundy" aria-hidden="true"><b></b><b></b><b></b></i></label><label class="customization-panel__theme" [attr.data-active]="preferences.theme() === 'purple'"><input type="radio" name="account-theme" value="purple" [checked]="preferences.theme() === 'purple'" (change)="setTheme('purple')"><span><strong>Фиолетовая</strong><small>Глубокая аметистовая палитра.</small></span><i class="customization-panel__theme-preview customization-panel__theme-preview--purple" aria-hidden="true"><b></b><b></b><b></b></i></label></div></section> }
        </div></div>
      </section></div>
    }
    @if (deleteConfirmOpen()) { <div class="dialog-backdrop" animate.leave="dialog-leave"><section class="dialog-card confirm-card" role="alertdialog" aria-modal="true"><h2>Удалить аккаунт?</h2><p>Ваш профиль будет удалён навсегда. Отменить это действие невозможно.</p><menu><button type="button" (click)="deleteConfirmOpen.set(false)">Отмена</button><button class="button button--danger" type="button" [disabled]="pending()" (click)="deleteProfile()">Удалить</button></menu></section></div> }
  `,
})
export class AccountDialogComponent {
  readonly open = input(false); readonly initialTab = input<AccountTab>('profile'); readonly closed = output<void>();
  protected readonly auth = inject(AuthStore); private readonly api = inject(ApiService); private readonly voice = inject(VoiceService); protected readonly preferences = inject(PreferencesService); private readonly notifications = inject(NotificationStore); private readonly router = inject(Router);
  protected readonly tabs: { id: AccountTab; label: string }[] = [{ id: 'profile', label: 'Профиль' }, { id: 'settings', label: 'Настройки' }, { id: 'security', label: 'Безопасность' }, { id: 'customization', label: 'Кастомизация' }];
  protected readonly tab = signal<AccountTab>('profile'); protected readonly pending = signal(false); protected readonly loading = signal(false); protected readonly sessionsLoading = signal(false); protected readonly sessions = signal<SecuritySession[]>([]); protected readonly progress = signal(0); protected readonly previewUrl = signal(''); protected readonly deleteConfirmOpen = signal(false); protected readonly inputs = signal<MediaDeviceInfo[]>([]); protected readonly outputs = signal<MediaDeviceInfo[]>([]); private selectedAvatar?: File;
  protected readonly profileForm = new FormGroup({ displayName: new FormControl(this.auth.user()?.display_name ?? '', { nonNullable: true, validators: [Validators.required, Validators.maxLength(50)] }) });
  protected readonly settingsForm = new FormGroup({ inputDeviceId: new FormControl(this.preferences.audio().inputDeviceId, { nonNullable: true }), outputDeviceId: new FormControl(this.preferences.audio().outputDeviceId, { nonNullable: true }), microphoneEnabled: new FormControl(this.preferences.audio().microphoneEnabled, { nonNullable: true }), debugErrors: new FormControl(this.preferences.web().debugErrors, { nonNullable: true }) });
  protected readonly passwordForm = new FormGroup({ password: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.minLength(6), Validators.maxLength(72)] }) });
  constructor() { effect(() => { if (this.open()) this.tab.set(this.initialTab()); }); this.settingsForm.valueChanges.pipe(takeUntilDestroyed(inject(DestroyRef))).subscribe(() => { const value = this.settingsForm.getRawValue(); this.preferences.updateAudio({ inputDeviceId: value.inputDeviceId, outputDeviceId: value.outputDeviceId, microphoneEnabled: value.microphoneEnabled }); this.preferences.updateWeb({ debugErrors: value.debugErrors }); }); }
  protected heading(): string { return this.tabs.find((item) => item.id === this.tab())?.label ?? 'Профиль'; }
  protected setTheme(theme: 'dark' | 'light' | 'forest' | 'burgundy' | 'purple'): void { this.preferences.setTheme(theme); }
  protected selectTab(tab: AccountTab): void { this.tab.set(tab); if (tab === 'settings') void this.loadDevices(false); if (tab === 'security') void this.loadSessions(); }
  protected canManageSecurity(): boolean { return this.auth.user()?.security?.can_manage ?? false; }
  protected closeBackdrop(event: MouseEvent): void { if (event.target === event.currentTarget) this.closed.emit(); }
  protected pickAvatar(event: Event): void { const input = event.target as HTMLInputElement; const file = input.files?.[0]; if (!file) return; if (!['image/png', 'image/jpeg', 'image/gif', 'image/webp'].includes(file.type)) { input.value = ''; this.notifications.error('Аватар должен быть jpeg, png, gif или webp'); return; } this.selectedAvatar = file; this.revokePreview(); this.previewUrl.set(URL.createObjectURL(file)); this.notifications.neutral('Предпросмотр обновлён. Нажмите «Сохранить», чтобы применить.'); }
  protected profileChanged(): boolean { return this.profileForm.controls.displayName.value.trim() !== this.auth.user()?.display_name || Boolean(this.selectedAvatar); }
  protected async saveProfile(): Promise<void> { if (this.profileForm.invalid || !this.profileChanged()) return; const name = this.profileForm.controls.displayName.value.trim(); if (![...name].length) return; this.pending.set(true); this.progress.set(this.selectedAvatar ? 1 : 0); try { const result = await lastValueFrom(this.api.updateProfile(name, this.selectedAvatar)); if (!result.user) throw new Error('Сервер не вернул профиль'); this.auth.setUser(result.user); this.selectedAvatar = undefined; this.revokePreview(); this.notifications.success('Профиль сохранён'); } catch (error) { this.notifications.error(error, 'Не удалось сохранить профиль'); } finally { this.pending.set(false); this.progress.set(0); } }
  protected async deleteAvatar(): Promise<void> { this.pending.set(true); try { this.auth.setUser(await firstValueFrom(this.api.deleteAvatar())); this.selectedAvatar = undefined; this.revokePreview(); this.notifications.success('Аватар удалён'); } catch (error) { this.notifications.error(error, 'Не удалось удалить аватар'); } finally { this.pending.set(false); } }
  protected async logout(): Promise<void> { this.pending.set(true); try { await this.voice.shutdown(); await this.auth.logout(); this.closed.emit(); await this.router.navigate(['/login']); } finally { this.pending.set(false); } }
  protected async deleteProfile(): Promise<void> { this.pending.set(true); try { await firstValueFrom(this.api.deleteProfile()); this.auth.clear(); await this.voice.shutdown(); this.closed.emit(); await this.router.navigate(['/register']); } catch (error) { this.notifications.error(error, 'Не удалось удалить аккаунт'); } finally { this.pending.set(false); } }
  protected async changePassword(): Promise<void> { if (this.passwordForm.invalid || !this.canManageSecurity()) return; this.pending.set(true); try { await firstValueFrom(this.api.changePassword(this.passwordForm.controls.password.value)); this.passwordForm.reset({ password: '' }); this.notifications.success('Пароль изменён'); } catch (error) { this.notifications.error(error, 'Не удалось сменить пароль'); } finally { this.pending.set(false); } }
  protected async loadSessions(): Promise<void> { if (!this.canManageSecurity()) return; this.sessionsLoading.set(true); try { this.sessions.set(await firstValueFrom(this.api.securitySessions())); await this.auth.ensureUser(true); } catch (error) { this.notifications.error(error, 'Не удалось загрузить устройства'); } finally { this.sessionsLoading.set(false); } }
  protected async revokeSession(session: SecuritySession): Promise<void> { if (session.current || !this.canManageSecurity()) return; this.pending.set(true); try { await firstValueFrom(this.api.revokeSecuritySession(session.id)); this.sessions.update((items) => items.filter((item) => item.id !== session.id)); this.notifications.success('Сеанс завершён'); } catch (error) { this.notifications.error(error, 'Не удалось завершить сеанс'); } finally { this.pending.set(false); } }
  protected async loadDevices(announce = true): Promise<void> { this.loading.set(true); try { const [inputs, outputs] = await Promise.all([Room.getLocalDevices('audioinput', false), Room.getLocalDevices('audiooutput', false)]); this.inputs.set(inputs); this.outputs.set(outputs); if (announce) this.notifications.success('Устройства обновлены'); } catch (error) { this.notifications.error(error, 'Не удалось получить список устройств'); } finally { this.loading.set(false); } }
  private revokePreview(): void { const value = this.previewUrl(); if (value) URL.revokeObjectURL(value); this.previewUrl.set(''); }
}
