port: 7880

rtc:
  use_external_ip: true
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50100

keys:
  replace-with-production-key: "replace-with-production-secret"

turn:
  enabled: true
  domain: turn.substituteme.space
  udp_port: 3478
  tls_port: 5349
  cert_file: /etc/letsencrypt/live/opentalk.substituteme.space/fullchain.pem
  key_file: /etc/letsencrypt/live/opentalk.substituteme.space/privkey.pem
